sudo: false
language: node_js
node_js:
  - 6
env:
  global:
    - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
cache:
  - node_modules
notifications:
  email:
    on_success: never
    on_failure: always
before_install:
  - npm config set progress=false
  - npm install -g npm@^3
install:
  - npm i
script:
  - npm start
  - npm run deploy
after_script:
  - npm test
